### ISSUE TITLE
Connect to arbitrary IP/port in VLAN using websockets

### ISSUE THREAD

**Issue by ysangkok** [benjamincburns/websockproxy#1]
It would be easier to connect native applications with apps in jor1k, if there was a way to connect the the websockproxy without having to deal with low-level stuff like ethernet and IP.

I am imagining booting jor1k and letting it get an IP. Now, for a native app to connect to the emulated machine, the websockproxy could let people connect over websockets to `http://websockproxyhost/<IP_in_VLAN>/<PORT>` which would make websockproxy start a TCP connection in the VLAN to the specified IP:PORT. This would make it really easy to connect native apps with machines in the VLAN using [websockify](https://github.com/kanaka/websockify).

**Comment by benjamincburns** [comment]
Wow, I only just now noticed this - I need to check my notifications more often!

I'd suggest submitting a pull request, but ideally this project will disappear in favour of a nodejs implementation. The best I can offer right now is to keep this issue open, and when I get around to finishing my port over to node, I'll close this one and open it in the correct repo.

**Comment by DawnofMan** [comment]
@benjamincburns I tried to setup apache reverse proxy for websocket like [http://aripratech.com/reverse-proxy-websockets-with-apache-httpd-server/](url). Eventually, it helps to send GET requests to websockproxy Tornado server but it still fails to get a response from the emulated VM. 
![image](https://user-images.githubusercontent.com/59739021/116424555-e6981800-a841-11eb-8302-a0cbe1803579.png)
![image](https://user-images.githubusercontent.com/59739021/116424614-f3b50700-a841-11eb-8c14-83cbfda39e79.png)

**Comment by benjamincburns** [comment]
Please don't hijack GitHub issues. This issue board is for issues pertaining to websockproxy. Your problem is with Apache configuration, not websockproxy, and has nothing to do with the parent issue.

**Comment by benjamincburns** [comment]
@DawnofMan Please don't hijack GitHub issues. This issue board is for issues pertaining to websockproxy. Your problem is with Apache configuration, not websockproxy, and has nothing to do with the parent issue. If you have an issue with a bug in websockproxy, please raise a new issue. For help with Apache I recommend asking for help on [Server Fault](https://serverfault.com/).

**Comment by DawnofMan** [comment]
@benjamincburns . I tried to explain what I am doing. The problem here is connecting to websockproxy (Tornado using websocket) to request VM. Title of this issue and "over websockets to http://websockproxyhost/<IP_in_VLAN>/<PORT>" which I am also trying to achieve. 
@ysangkok Could you explain how did you achieve this through websockify?

**Comment by benjamincburns** [comment]
@DawnofMan it wasn't clear from your original comment that you were trying to achieve the same outcome as the OP of this issue. However, I already [replied to you on the other ticket where you commented about this](https://github.com/s-macke/jor1k/issues/155#issuecomment-824592968). As I said over there, what you're trying to achieve isn't possible with websockproxy today. You'd need to submit a fairly major PR to make this possible.

**Comment by ysangkok** [comment]
Closing since this is unactionable as it would be a major change as previously noted in this thread.
