### ISSUE TITLE
Dockerise websock proxy with DNS, DHCP, and NAT

### ISSUE THREAD

**Issue by benjamincburns** [benjamincburns/websockproxy#3]
Per #2, people need an easy way to self host their own websockproxy instance. Docker seems like a great fit for this.

cc @erronjason & @bsapwindows & @s-macke

**Comment by erronjason** [comment]
Yeah man, I don't currently have anything docker-wise; but I'd be entirely down to contribute.

**Comment by bsapwindows** [comment]
I appreciate the work you've done, now I understand current state is if the user wants a self hosted relay he has to deal with different platforms, and Docker does look pretty ideal for that. But I think it's safe to mention that the size of Docker Toolbox (for Windows) is 170MB, and it requires installation and extra Docker related knowledge. It's not so different from running a virtual machine via Virtualbox. What I did with jor1k is clean and simple, I download jor1k and jor1k-sysroot (7+72MB), extract them, download [mongoose](https://www.cesanta.com/mongoose) (200KB+), put it under jor1k root folder and run, just like dealing with some static html files. No further moves required. If I'm done playing with it, just delete the whole folder. I wish I could do the same (download and run) with the virtual switch so newbies like me can enjoy jor1k without hassle. (After I found out I can use `jor1kgui.ethernet` in Chrome console, I don't even need to download jor1k anymore.)

Besides, Docker images are more powerful than jor1k, aren't they? You can have all the tools you need in a base image, with network enabled, faster CPU, etc. To be honest, if I had docker installed, I don't think I'd use jor1k in the first place..

**Comment by erronjason** [comment]
I feel it's a bit short sighted to assume that everyone is going to be running the whole setup locally just for themselves. In this manner (dockerizing), you could throw the image on dotCloud or tutum and have your own private tunnel without the knowledge of re-creating the network portion. Granted, other virtualization that requires downloading large binaries is typically more powerful, but few people are using jor1k simply for virtualization, or creating a network relay locally just for themselves. I feel like keeping the barrier of entry low is kinda the spirit of virtualization in the browser we're going for :]
The amount of folks going through Ben's relay has got to be a decent sized number, and if an organization like a school wanted to use jor1k for their own purposes, I'm sure he'd appreciate them hosting/paying for their own relay. I say we should give them the chance to do so easily.
On the note of the privileged flag, it's as simple as running `docker run ourdockerimage --privileged=true`.

Unrelated, in lieu of mongoose, try using "python -m SimpleHTTPServer 80" in the directory. It's a nice platform-agnostic way of running a tiny server for a directory.

**Comment by bsapwindows** [comment]
I...I still believe in that people could use jor1k to decentralize the web :persevere: And "everyone is going to be running the whole setup locally" is pretty essential to do so. Of couse, users still can have nice things like a Docker image to make their life simpler. But I bet they'll find it bloated, since all they want is to set up an own relay, 170MB's Docker provides more functions than that.


About dotCloud . To me, many jor1k instances are going to connect to a single node without using user's own network as default doesn't sound so P2P. According to the [Structural Holes](https://en.wikipedia.org/wiki/Social_network#Structural_holes) theory, I think using a cloud service should be avoided when designing a P2P network, users should gain as much control as possible.

**Comment by erronjason** [comment]
I understand what you mean, but I think the decision here has been made, and isn't really a time to talk about the semantics of said decision. Decentralization isn't the main goal here, though I encourage you to look at https://github.com/getlantern/lantern or something of that sort.

If you'd like to assist on this particular issue, I'd love to have the documented steps you took to create the local proxy in order to automate them in docker (or simply a setup script that can be run on a VM).

**Comment by bsapwindows** [comment]
Er, I understand that. I was just a bit exited about my silly idea. Sorry if I sounded unreasonable...
I'm still learning some basics, nothing particular. Anyway, thank you for you kindness, I appreciate it :smile:

**Comment by benjamincburns** [comment]
As the maintainer of the project I agree that decentralisation isn't the main goal - but I can't say that I've made any firm decisions, and I'm certainly happy to debate semantics insofar as it's productive to do so. Doing so can bring to light interesting use cases, such as the "VPN in a box" idea you mention, @erronjason.

That said, I don't see how websockproxy or jor1k can be made to achieve your goals, @bsapwindows, without rather large changes to the browser and its underlying security model. Network support for jor1k is modeled in a centralised way because that is the only model which the browser supports.

I'd be very happy to support some effort to provide a broader decentralised network model outside of the browser, but due to heavy constraints on my time (I'm stealing away right now just to write this) any support I could provide would be quite minimal. Also if that work is proposed, I recommend doing so by raising an issue on s-macke/jor1k.

**Comment by bsapwindows** [comment]
Well, I didn't mean browser itself could do the trick. But a self-hosted relay will, a docker image in this case. So technically using docker will achieve my goal, I'm just not so fond of using another virtualization tool for it.
I do realize I was twisting where this issue is going. I don't even understand what I was talking about if you ask me. So please don't worry about the decentralization stuff, keep focusing on dockerization. If I need further help on setting up a relay on Windows without docker, I'll just open a new issue cheekily :smile: And thanks for your time Ben

**Comment by benjamincburns** [comment]
@erronjason & @bsapwindows - I finally got around to adding this. Docker image is up on docker hub at `benjamincburns/jor1k-relay` and simple "getting started" info can be found in the project README.

Let me know if you run into any troubles.
